name: sazzadshopno
description: Resume of Sazzad Hossain.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.0
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
